
server:
 servlet:
   context-path: /SpringBoot
spring:
 datasource: 
   url: jdbc:mysql://localhost/employee_portal
   username: root
   password: 12345
   driver-class-name : com.mysql.jdbc.Driver
   type: org.apache.tomcat.jdbc.pool.DataSource
